[package]
name = "example"
version = "0.1.0"
edition = "2018"
authors = ["ronanyeah"]
repository = "https://github.com/ronanyeah/rust-hasura"
readme = "README.md"
keywords = ["rust"]
categories = ["rust"]

[dependencies]
juniper = "0.14.2"
graphql_client = "0.8.0"
serde = "1.0.104"
serde_json = "1.0.47"
uuid_foo = { package = "uuid", version = "0.7.4", features = ["serde"] }
jsonwebtoken = "7.0.1"
bcrypt = "0.6.1"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
actix-web = "2.0.0"
futures = "0.3.4"
actix-http = "1.0.1"
actix-rt = "1.0.0"
envy = "0.4.1"

[[bin]]
name = "example"
path = "src/main.rs"
