[package]
name = "rust-hasura"
version = "0.1.0"
edition = "2018"
authors = ["ronanyeah"]
repository = "https://github.com/ronanyeah/rust-hasura"
readme = "README.md"
keywords = ["rust"]
categories = ["rust"]

[dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper" }
graphql_client = "0.9.0"
serde = "1.0.117"
serde_json = "1.0.59"
uuid_foo = { package = "uuid", version = "0.8.1", features = ["serde"] }
jsonwebtoken = "7.2.0"
reqwest = { version = "0.10.8", features = ["json"] }
futures = "0.3.7"
envy = "0.4.1"
actix-web = "3.1.0"
actix-http = "2.0.0"
actix-rt = "1.1.1"
async-std = "1.6.5"

[[bin]]
name = "example"
path = "src/main.rs"
