[package]
name = "example"
version = "0.1.0"
edition = "2018"
authors = ["ronanyeah"]
repository = "https://github.com/ronanyeah/rust-hasura"
readme = "README.md"
keywords = ["rust"]
categories = ["rust"]

[dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper" }
graphql_client = "0.9.0"
serde = "1.0.106"
serde_json = "1.0.51"
uuid_foo = { package = "uuid", version = "0.8.1", features = ["serde"] }
jsonwebtoken = "7.1.0"
bcrypt = "0.7.0"
reqwest = { version = "0.10.4", features = ["json"] }
actix-web = "2.0.0"
futures = "0.3.4"
actix-http = "1.0.1"
actix-rt = "1.1.0"
envy = "0.4.1"

[[bin]]
name = "example"
path = "src/main.rs"
